version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: task-backend:local
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  frontend:
    build:
      context: ./frontend
    image: task-frontend:local
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
