name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: Smoke test (prints date, actor and repo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print run info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Date (UTC): $(date -u)"

      - name: Mark success
        run: echo "CI smoke test succeeded"
