name: Task Management System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Backend Build
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
        
    - name: Backend Check
      run: |
        cd backend
        node -v
        
    # Frontend Build
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Frontend Build
      run: |
        cd frontend
        npm run build --if-present